workflows:
  expo-multi-platform:
    name: Expo iOS & Android
    environment:
      node: 18.16.0
    scripts:
      - npm install -g eas-cli
      - npm install
      - eas build --platform all --non-interactive
    artifacts:
      - build/**/*.apk
      - build/**/*.aab
      - build/**/*.ipa
