workflows:
  build-ios-ipa:
    name: Build iOS IPA Only
    environment:
      vars:
        EXPO_TOKEN: 7mMPJVDASVRKrMxuj0DaRFJnRiyBN4sHZ-nxsmOv
    scripts:
      - name: Install dependencies
        script: |
          npm install -g eas-cli
          npm install
      - name: Build iOS IPA using EAS
        script: |
          eas build --platform ios --profile ios --non-interactive
    artifacts:
      - build/**/ios/**/*.ipa
