workflows:
  expo-multi-platform:
    name: Expo iOS & Android
    environment: 
     groups:
        - x
    node: 18.16.0
    scripts:
      - npm install -g eas-cli
      - npm install
      - eas build --platform all --non-interactive --token $exp
    artifacts:
      - build/**/*.apk
      - build/**/*.aab
      - build/**/*.ipa
